// Package model contains the types for schema 'public'.
package model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// Block represents a row from 'public.blocks'.
type Block struct {
	ID     int64          `json:"id"`     // id
	Height sql.NullInt64  `json:"height"` // height
	Data   sql.NullString `json:"data"`   // data

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Block exists in the database.
func (b *Block) Exists() bool {
	return b._exists
}

// Deleted provides information if the Block has been deleted from the database.
func (b *Block) Deleted() bool {
	return b._deleted
}

// Insert inserts the Block to the database.
func (b *Block) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if b._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	const sqlstr = `INSERT INTO public.blocks (` +
		`height, data` +
		`) VALUES (` +
		`$1, $2` +
		`) RETURNING id`

	// run query
	XOLog(sqlstr, b.Height, b.Data)
	err = db.QueryRow(sqlstr, b.Height, b.Data).Scan(&b.ID)
	if err != nil {
		return err
	}

	// set existence
	b._exists = true

	return nil
}

// Update updates the Block in the database.
func (b *Block) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !b._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if b._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.blocks SET (` +
		`height, data` +
		`) = ( ` +
		`$1, $2` +
		`) WHERE id = $3`

	// run query
	XOLog(sqlstr, b.Height, b.Data, b.ID)
	_, err = db.Exec(sqlstr, b.Height, b.Data, b.ID)
	return err
}

// Save saves the Block to the database.
func (b *Block) Save(db XODB) error {
	if b.Exists() {
		return b.Update(db)
	}

	return b.Insert(db)
}

// Upsert performs an upsert for Block.
//
// NOTE: PostgreSQL 9.5+ only
func (b *Block) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if b._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.blocks (` +
		`id, height, data` +
		`) VALUES (` +
		`$1, $2, $3` +
		`) ON CONFLICT (id) DO UPDATE SET (` +
		`id, height, data` +
		`) = (` +
		`EXCLUDED.id, EXCLUDED.height, EXCLUDED.data` +
		`)`

	// run query
	XOLog(sqlstr, b.ID, b.Height, b.Data)
	_, err = db.Exec(sqlstr, b.ID, b.Height, b.Data)
	if err != nil {
		return err
	}

	// set existence
	b._exists = true

	return nil
}

// Delete deletes the Block from the database.
func (b *Block) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !b._exists {
		return nil
	}

	// if deleted, bail
	if b._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.blocks WHERE id = $1`

	// run query
	XOLog(sqlstr, b.ID)
	_, err = db.Exec(sqlstr, b.ID)
	if err != nil {
		return err
	}

	// set deleted
	b._deleted = true

	return nil
}

// BlocksQuery returns offset-limit rows from 'public.blocks' filte by filter,
// ordered by "id" in descending order.
func BlockFilter(db XODB, filter string, offset, limit int) ([]*Block, error) {
	sqlstr := `SELECT ` +
		`id, height, data` +
		`FROM public.blocks `

	if filter != "" {
		sqlstr = sqlstr + " WHERE " + filter
	}

	sqlstr = sqlstr + " order by id desc offset $1 limit $2"

	XOLog(sqlstr, offset, limit)
	q, err := db.Query(sqlstr, offset, limit)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Block
	for q.Next() {
		b := Block{}

		// scan
		err = q.Scan(&b.ID, &b.Height, &b.Data)
		if err != nil {
			return nil, err
		}

		res = append(res, &b)
	}

	return res, nil
} // BlockByHeight retrieves a row from 'public.blocks' as a Block.
//
// Generated from index 'blocks_height_key'.
func BlockByHeight(db XODB, height sql.NullInt64) (*Block, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, height, data ` +
		`FROM public.blocks ` +
		`WHERE height = $1`

	// run query
	XOLog(sqlstr, height)
	b := Block{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, height).Scan(&b.ID, &b.Height, &b.Data)
	if err != nil {
		return nil, err
	}

	return &b, nil
}

// BlockByID retrieves a row from 'public.blocks' as a Block.
//
// Generated from index 'blocks_pkey'.
func BlockByID(db XODB, id int64) (*Block, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, height, data ` +
		`FROM public.blocks ` +
		`WHERE id = $1`

	// run query
	XOLog(sqlstr, id)
	b := Block{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&b.ID, &b.Height, &b.Data)
	if err != nil {
		return nil, err
	}

	return &b, nil
}
