// Package model contains the types for schema 'public'.
package model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
	"fmt"

	"github.com/lib/pq"
)

// TmBlockChain represents a row from 'public.tm_block_chain'.
type TmBlockChain struct {
	ID        int64          `json:"id"`         // id
	ChainID   sql.NullString `json:"chain_id"`   // chain_id
	Height    sql.NullInt64  `json:"height"`     // height
	NumTxs    sql.NullInt64  `json:"num_txs"`    // num_txs
	Data      sql.NullString `json:"data"`       // data
	Time      pq.NullTime    `json:"time"`       // time
	CreatedAt pq.NullTime    `json:"created_at"` // created_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the TmBlockChain exists in the database.
func (tbc *TmBlockChain) Exists() bool {
	return tbc._exists
}

// Deleted provides information if the TmBlockChain has been deleted from the database.
func (tbc *TmBlockChain) Deleted() bool {
	return tbc._deleted
}

// Insert inserts the TmBlockChain to the database.
func (tbc *TmBlockChain) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if tbc._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	const sqlstr = `INSERT INTO public.tm_block_chain (` +
		`chain_id, height, num_txs, data, time, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`) RETURNING id`

	// run query
	XOLog(sqlstr, tbc.ChainID, tbc.Height, tbc.NumTxs, tbc.Data, tbc.Time, tbc.CreatedAt)
	err = db.QueryRow(sqlstr, tbc.ChainID, tbc.Height, tbc.NumTxs, tbc.Data, tbc.Time, tbc.CreatedAt).Scan(&tbc.ID)
	if err != nil {
		return err
	}

	// set existence
	tbc._exists = true

	return nil
}

// Update updates the TmBlockChain in the database.
func (tbc *TmBlockChain) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !tbc._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if tbc._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.tm_block_chain SET (` +
		`chain_id, height, num_txs, data, time, created_at` +
		`) = ( ` +
		`$1, $2, $3, $4, $5, $6` +
		`) WHERE id = $7`

	// run query
	XOLog(sqlstr, tbc.ChainID, tbc.Height, tbc.NumTxs, tbc.Data, tbc.Time, tbc.CreatedAt, tbc.ID)
	_, err = db.Exec(sqlstr, tbc.ChainID, tbc.Height, tbc.NumTxs, tbc.Data, tbc.Time, tbc.CreatedAt, tbc.ID)
	return err
}

// Save saves the TmBlockChain to the database.
func (tbc *TmBlockChain) Save(db XODB) error {
	if tbc.Exists() {
		return tbc.Update(db)
	}

	return tbc.Insert(db)
}

// Upsert performs an upsert for TmBlockChain.
//
// NOTE: PostgreSQL 9.5+ only
func (tbc *TmBlockChain) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if tbc._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.tm_block_chain (` +
		`id, chain_id, height, num_txs, data, time, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7` +
		`) ON CONFLICT (id) DO UPDATE SET (` +
		`id, chain_id, height, num_txs, data, time, created_at` +
		`) = (` +
		`EXCLUDED.id, EXCLUDED.chain_id, EXCLUDED.height, EXCLUDED.num_txs, EXCLUDED.data, EXCLUDED.time, EXCLUDED.created_at` +
		`)`

	// run query
	XOLog(sqlstr, tbc.ID, tbc.ChainID, tbc.Height, tbc.NumTxs, tbc.Data, tbc.Time, tbc.CreatedAt)
	_, err = db.Exec(sqlstr, tbc.ID, tbc.ChainID, tbc.Height, tbc.NumTxs, tbc.Data, tbc.Time, tbc.CreatedAt)
	if err != nil {
		return err
	}

	// set existence
	tbc._exists = true

	return nil
}

// Delete deletes the TmBlockChain from the database.
func (tbc *TmBlockChain) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !tbc._exists {
		return nil
	}

	// if deleted, bail
	if tbc._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.tm_block_chain WHERE id = $1`

	// run query
	XOLog(sqlstr, tbc.ID)
	_, err = db.Exec(sqlstr, tbc.ID)
	if err != nil {
		return err
	}

	// set deleted
	tbc._deleted = true

	return nil
}

// TmBlockChainsQuery returns offset-limit rows from 'public.tm_block_chain' filte by filter,
// ordered by "id" in descending order.
func TmBlockChainFilter(db XODB, filter, sort string, offset, limit int64) ([]*TmBlockChain, error) {
	sqlstr := `SELECT ` +
		`id, chain_id, height, num_txs, data, time, created_at` +
		` FROM public.tm_block_chain `

	if filter != "" {
		sqlstr = sqlstr + " WHERE " + filter
	}

	if sort != "" {
		sqlstr = sqlstr + " " + sort
	}

	if limit > 0 {
		sqlstr = sqlstr + fmt.Sprintf(" offset %d limit %d", offset, limit)
	}

	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*TmBlockChain
	for q.Next() {
		tbc := TmBlockChain{
			_exists: true,
		}

		// scan
		err = q.Scan(&tbc.ID, &tbc.ChainID, &tbc.Height, &tbc.NumTxs, &tbc.Data, &tbc.Time, &tbc.CreatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &tbc)
	}

	return res, nil
}

// TmBlockChainByChainIDHeight retrieves a row from 'public.tm_block_chain' as a TmBlockChain.
//
// Generated from index 'tm_block_chain_chain_id_height_idx'.
func TmBlockChainByChainIDHeight(db XODB, chainID sql.NullString, height sql.NullInt64) (*TmBlockChain, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, chain_id, height, num_txs, data, time, created_at ` +
		`FROM public.tm_block_chain ` +
		`WHERE chain_id = $1 AND height = $2`

	// run query
	XOLog(sqlstr, chainID, height)
	tbc := TmBlockChain{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, chainID, height).Scan(&tbc.ID, &tbc.ChainID, &tbc.Height, &tbc.NumTxs, &tbc.Data, &tbc.Time, &tbc.CreatedAt)
	if err != nil {
		return nil, err
	}

	return &tbc, nil
}

// TmBlockChainsByChainID retrieves a row from 'public.tm_block_chain' as a TmBlockChain.
//
// Generated from index 'tm_block_chain_chain_id_idx'.
func TmBlockChainsByChainID(db XODB, chainID sql.NullString) ([]*TmBlockChain, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, chain_id, height, num_txs, data, time, created_at ` +
		`FROM public.tm_block_chain ` +
		`WHERE chain_id = $1`

	// run query
	XOLog(sqlstr, chainID)
	q, err := db.Query(sqlstr, chainID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*TmBlockChain{}
	for q.Next() {
		tbc := TmBlockChain{
			_exists: true,
		}

		// scan
		err = q.Scan(&tbc.ID, &tbc.ChainID, &tbc.Height, &tbc.NumTxs, &tbc.Data, &tbc.Time, &tbc.CreatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &tbc)
	}

	return res, nil
}

// TmBlockChainByID retrieves a row from 'public.tm_block_chain' as a TmBlockChain.
//
// Generated from index 'tm_block_chain_pkey'.
func TmBlockChainByID(db XODB, id int64) (*TmBlockChain, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, chain_id, height, num_txs, data, time, created_at ` +
		`FROM public.tm_block_chain ` +
		`WHERE id = $1`

	// run query
	XOLog(sqlstr, id)
	tbc := TmBlockChain{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&tbc.ID, &tbc.ChainID, &tbc.Height, &tbc.NumTxs, &tbc.Data, &tbc.Time, &tbc.CreatedAt)
	if err != nil {
		return nil, err
	}

	return &tbc, nil
}
